---
- name: Ensure MariaDB-server and Pymysql is installed.
  ansible.builtin.package:
    name:
      - mariadb-server
      - python3-PyMySQL
    state: present

- name: Ensure MariaDB service is enabled and started
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Create webappdb database
  community.mysql.mysql_db:
    name: webappdb
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create webappuser and grant privileges
  community.mysql.mysql_user:
    name: webappuser
    password: "{{ mysql_webapp_password }}"
    priv: "webappdb.*:ALL"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Copy all .md files to deploy's home
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/deploy/"
    owner: deploy
    group: deploy
    mode: '0644'
  with_fileglob:
    - "files/*.md"
